ignored:
# it cannot parse `FROM ${BASE_IMAGE}`
- DL3006
# alpine doesn't keep old versions around, so we cannot rely on package pinning,
# which is also very tedious and is deemed uncessary
- DL3018
# also disable pining checks for ubuntu, as it currently deemed uncessary and,
# in most cases, packages are installed via scripts and those don't get checked
# (albeit, ubuntu repos tend to keep old versions around)
- DL3008
# similar as the two above, disable package version pinning for dnf
- DL3041
