name: PR Check
on:
  pull_request: {}
  push:
    branches:
    - main

jobs:
  lint:
    name: Run static checks
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: docker://quay.io/cilium/image-maker:1755027480-74de989@sha256:be90a4b1ccb7553e54f8eb8224a82a5f886cdbd6057dafc9d36205615f46d696
        name: Run make lint
        with:
          entrypoint: sh
          args: -c "git config --global --add safe.directory /github/workspace && make lint"
