name: PR Check
on:
  pull_request: {}
  push:
    branches:
    - master

jobs:
  lint:
    name: Run static checks
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: docker://quay.io/cilium/image-maker:1751527462-bb24228@sha256:b17984cf427f921c65409816b8890bbf893ea44a42c226a3a56aca90f3205939
        name: Run make lint
        with:
          entrypoint: sh
          args: -c "git config --global --add safe.directory /github/workspace && make lint"
