name: PR Check
on:
  pull_request: {}
  push:
    branches:
    - master

jobs:
  lint:
    name: Run static checks
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: docker://quay.io/cilium/image-maker:1751996942-195b4d9@sha256:9ede3d0c9202b4feaa88c459e57b77bbb5dca422db065a387e58263608491c24
        name: Run make lint
        with:
          entrypoint: sh
          args: -c "git config --global --add safe.directory /github/workspace && make lint"
